apiVersion: v1
kind: Service
metadata:
  name: svc1-svc
spec:
  type: NodePort
  selector:
    app: svc1-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30080
      port: 2346
      targetPort: 8080