apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-svc2-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-svc2-app
  template:
    metadata:
      labels:
        app: eureka-svc2-app
    spec:
      containers:
        - name: eureka-svc2-container
          image: registry.localhost:5000/eureka-svc2
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: ${EUREKA_URI:http://eureka-server-service.default.svc.cluster.local:2349/eureka}
          imagePullPolicy: Always