apiVersion: v1
kind: Service
metadata:
  name: eureka-svc2-svc
spec:
  type: NodePort
  selector:
    app: eureka-svc2-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30002
      port: 2350
      targetPort: 8081