apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  type: NodePort
  selector:
    app: eureka-server-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30001
      port: 2349
      targetPort: 8761