apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      labels:
        app: consumer-app
    spec:
      containers:
        - name: consumer-container
          image: registry.localhost:5000/consumer
          env:
            - name: SPRING_RABBITMQ_HOST
              value: definition.default.svc.cluster.local
            - name: SPRING_RABBITMQ_USERNAME
              value: default_user_lL8bFSvEU6CjBu-EQRw
            - name: SPRING_RABBITMQ_PASSWORD
              value: nzjc6Mu_J_VlcFmOKE7A5swcI_edozHO
          imagePullPolicy: Always
