apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://user:1234@localhost:5672"
    - name: requeueInFailure
      value: true