apiVersion: v1
kind: Service
metadata:
  name: producer-svc
spec:
  type: NodePort
  selector:
    app: producer-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30003
      port: 2351
      targetPort: 8989
