apiVersion: v1
kind: Service
metadata:
  name: dapr-svc2-svc
spec:
  type: NodePort
  selector:
    app: dapr-svc2-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30082
      port: 2348
      targetPort: 8081