apiVersion: v1
kind: Service
metadata:
  name: dapr-svc1-svc
spec:
  type: NodePort
  selector:
    app: dapr-svc1-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30079
      port: 2345
      targetPort: 8080