apiVersion: v1
kind: Service
metadata:
  name: dapr-producer-svc
spec:
  type: NodePort
  selector:
    app: dapr-producer-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30004
      port: 2352
      targetPort: 8080