version: "3.8"

services:
  mongodb:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    volumes:
      - ./.docker/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=S3cr3t