apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc1-app
  template:
    metadata:
      labels:
        app: svc1-app
    spec:
      containers:
        - name: svc1-container
          image: registry.localhost:5000/svc1