apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc2-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc2-app
  template:
    metadata:
      labels:
        app: svc2-app
    spec:
      containers:
        - name: svc2-container
          image: registry.localhost:5000/svc2
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: svc2-config
                  key: SVC_URL