apiVersion: v1
kind: Service
metadata:
  name: svc2-svc
spec:
  type: NodePort
  selector:
    app: svc2-app
  ports:
    - name: http
      protocol: TCP
      nodePort: 30081
      port: 2347
      targetPort: 8081